<script setup lang="ts">
import { computed } from 'vue'
import {
  Sparkles,
  MessageSquare,
  Plus,
  Search,
  Wrench,
  LayoutGrid,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  Paperclip,
  X,
  Menu,
  Copy,
  Check,
  BookOpen,
  Layers,
  Globe,
  Activity,
  Square,
  Sun,
  Moon,
  Clock,
  Link,
  ExternalLink,
  RefreshCw,
  PanelRight,
  User,
  TriangleAlert,
  Code,
  Server,
  KeyRound,
  Download,
  Pencil,
  Trash2,
  ShieldCheck,
  GitBranch,
  ArrowUpRight,
  SlidersHorizontal,
} from '@lucide/vue'
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 20 })
const icons = {
  spark: Sparkles,
  chat: MessageSquare,
  plus: Plus,
  search: Search,
  tool: Wrench,
  grid: LayoutGrid,
  arrow: ArrowUp,
  down: ArrowDown,
  right: ChevronRight,
  attach: Paperclip,
  close: X,
  menu: Menu,
  copy: Copy,
  check: Check,
  book: BookOpen,
  layers: Layers,
  globe: Globe,
  pulse: Activity,
  stop: Square,
  sun: Sun,
  moon: Moon,
  clock: Clock,
  link: Link,
  external: ExternalLink,
  refresh: RefreshCw,
  panel: PanelRight,
  user: User,
  alert: TriangleAlert,
  code: Code,
  server: Server,
  key: KeyRound,
  download: Download,
  edit: Pencil,
  trash: Trash2,
  shield: ShieldCheck,
  branch: GitBranch,
  diagonal: ArrowUpRight,
  settings: SlidersHorizontal,
}
const icon = computed(() => icons[props.name as keyof typeof icons] ?? Sparkles)
</script>
<template><component :is="icon" :size="size" :stroke-width="1.65" aria-hidden="true" /></template>
